In [1]:
import pandas as pd
import json
import http.client
import random
from api_keys import attom_data_key

In [18]:
a = pd.read_csv("../data/rawdata/Harris_County.csv",header=None)
zips =  list(a[0])

In [3]:
conn = http.client.HTTPSConnection("search.onboard-apis.com") 

headers = { 
    'accept': "application/json", 
    'apikey': attom_data_key
} 

total_Addresses = []
county_Zip_Adds = pd.DataFrame(data={"zip":"", "address":"", "lat":"", "lng":""}, index = [0])

for i in range(0,len(zips)):
        print(f"Harris, {zips[i]}")
        for tries in range(1,11):
            try:
                pages = []
                page_Num = 2
                conn.request("GET", f"https://search.onboard-apis.com/propertyapi/v1.0.0/property/address?postalcode={zips[i]}&page=1&pagesize=2000", headers=headers)
                res = conn.getresponse().read().decode()
                data = json.loads(res)
                page_Size = len(data["property"])
                total = data["status"]["total"]
                total_Addresses.append(total)
                print(f"There are {total} number of addresses known in this zipcode.")
                total -= 2000
                while total > 0:
                    pages.append(page_Num)
                    page_Num += 1
                    total -= 2000
                print(f"\tNum Results: {page_Size} for page 1")
                if page_Size > 0:
                    df = pd.DataFrame(data={"zip":"", "address":"", "lat":"", "lng":""}, index = [k for k in range(page_Size)])
                    for j in range(page_Size):
                        df.iat[j, 0] = data['property'][j]['address']['postal1']
                        df.iat[j, 1] = data['property'][j]['address']['oneLine']
                        df.iat[j, 2] = data['property'][j]['location']['latitude']
                        df.iat[j, 3] = data['property'][j]['location']['longitude']
                    df.drop_duplicates(subset="address",inplace=True)
                    df = df.reset_index(drop=True)
                    county_Zip_Adds = county_Zip_Adds.append(df.copy(),ignore_index = True)
                for c in pages:
                    for add_tries in range(1,11):
                        try:
                            conn.request("GET", f"https://search.onboard-apis.com/propertyapi/v1.0.0/property/address?postalcode={zips[i]}&page={c}&pagesize=2000", headers=headers)
                            res = conn.getresponse().read().decode()
                            data = json.loads(res)
                            page_Size = len(data["property"])
                            print(f"\tNum Results: {page_Size} for page {c}")
                            if page_Size > 0:
                                df = pd.DataFrame(data={"zip":"", "address":"", "lat":"", "lng":""}, index = [k for k in range(page_Size)])
                                for j in range(page_Size):
                                    df.iat[j, 0] = data['property'][j]['address']['postal1']
                                    df.iat[j, 1] = data['property'][j]['address']['oneLine']
                                    df.iat[j, 2] = data['property'][j]['location']['latitude']
                                    df.iat[j, 3] = data['property'][j]['location']['longitude']
                                df.drop_duplicates(subset="address",inplace=True)
                                df = df.reset_index(drop=True)
                                county_Zip_Adds = county_Zip_Adds.append(df.copy(),ignore_index = True)
                            break
                        except:
                            print(f"\tTry {add_tries} for page {c} didn't parse correctly. Trying again up to 10 times total.")
                break
            except:
                    print(f"\tTry {tries} for page 1 didn't parse correctly. Trying again up to 10 times total.")
county_Zip_Adds = county_Zip_Adds.drop([0])
county_Zip_Adds = county_Zip_Adds.reset_index(drop=True)

Harris, 77002
There are 2945 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 945 for page 2
Harris, 77004
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77003
There are 5633 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Num Results: 1633 for page 3
Harris, 77006
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 4 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 8064 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 64 for page 5
Harris, 77005
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 8809 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Try 1 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 809 for page 5
Harris, 77008
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 4
	Try 1 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 5
Harris, 77007
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77010
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 85 number of addresses known in this zipcode.
	Num Results: 85 for page 1
Harris, 77009
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 4
	Try 1 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Try 4 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 5
Harris, 77012
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 5418 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Num Results: 1418 for page 3
Harris, 77011
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 6109 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 4 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Num Results: 1999 for page 3
	Num Results: 109 for page 4
Harris, 77014
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 4 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 5 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 6 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 7 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 7451 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Num Results: 1451 for page 4
Harris, 77013
There are 4311 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Num Results: 311 for page 3
Harris, 77016
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77015
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Try 1 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 5
Harris, 77018
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77017
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 8623 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 623 for page 5
Harris, 77020
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1

	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77019
There are 8250 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 4
	Num Results: 250 for page 5
Harris, 77022
There are 9826 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Try 1 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 1826 for page 5
Harris, 77021
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Num Results: 1999 for page 4
	Try 1 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 5
Harris, 77024
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77023
There are 7727 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 4 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 1727 for page 4
Harris, 77026
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77025
There are 8231 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 4 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 5 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 6 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 231 for page 5
Harris, 77028
There are 10000 number of addresses known in this zipcode.
	Num Results: 1999 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Try 1 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 5
Harris, 77027
There are 5277 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Num Results: 1277 for page 3
Harris, 77030
There are 4093 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Num Results: 93 for page 3
Harris, 77029
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 8011 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 4
	Num Results: 11 for page 5
Harris, 77032
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 5184 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Num Results: 1184 for page 3
Harris, 77031
There are 3873 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 1873 for page 2
Harris, 77034
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 8342 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 342 for page 5
Harris, 77033
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77036
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 4
	Try 1 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Try 4 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 5
Harris, 77035
There are 8887 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 887 for page 5
Harris, 77038
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 7968 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 1968 for page 4
Harris, 77037
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.

	Try 2 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 6537 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Num Results: 537 for page 4
Harris, 77040
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77039
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 8650 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 650 for page 5
Harris, 77042
There are 7841 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 1841 for page 4
Harris, 77041
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77044
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77043
There are 8490 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 490 for page 5
Harris, 77046
There are 429 number of addresses known in this zipcode.
	Num Results: 429 for page 1
Harris, 77045
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 4
	Try 1 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 5
Harris, 77048
There are 7335 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Num Results: 1335 for page 4
Harris, 77047
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 4 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 5 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 6 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77050
There are 1963 number of addresses known in this zipcode.
	Num Results: 1963 for page 1
Harris, 77049
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Try 1 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 5
Harris, 77051
There are 7696 number of addresses known in this zipcode.
	Num Results: 1999 for page 1
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Num Results: 1696 for page 4
Harris, 77054
There are 5252 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 1252 for page 3
Harris, 77053
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77056
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 7777 number of addresses known in this zipcode.
	Num Results: 1999 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 4 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 5 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 1777 for page 4
Harris, 77055
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77058
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 4916 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Num Results: 916 for page 3
Harris, 77057
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Try 1 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 5
Harris, 77060
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 6153 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Num Results: 153 for page 4
Harris, 77059

There are 6747 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Num Results: 747 for page 4
Harris, 77062
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 8856 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 1999 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 856 for page 5
Harris, 77061
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 5177 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 1177 for page 3
Harris, 77064
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 4 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 5 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 4
	Try 1 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 5
Harris, 77063
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 7768 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Num Results: 1768 for page 4
Harris, 77066
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77065
There are 9099 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 4
	Num Results: 1099 for page 5
Harris, 77068
There are 3794 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 1794 for page 2
Harris, 77067
There are 6403 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Num Results: 403 for page 4
Harris, 77070
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 4
	Try 1 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 5
Harris, 77069
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 6210 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Num Results: 210 for page 4
Harris, 77072
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77071
There are 7993 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Num Results: 1993 for page 4
Harris, 77074
There are 7972 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 1972 for page 4
Harris, 77073
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 4 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77076
There are 8332 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 332 for page 5
Harris, 77075
There are 10000 number of addresses known in this zipcode.
	Num Results: 1999 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77078
There are 5543 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Num Results: 1543 for page 3
Harris, 77077
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 2 didn't parse correctly. Trying again up to 10 times total.

	Try 4 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77080
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 10000 number of addresses known in this zipcode.
	Num Results: 1999 for page 1
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Try 1 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Try 4 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 5
Harris, 77079
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Try 1 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 1999 for page 5
Harris, 77082
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 4
	Try 1 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 5
Harris, 77081
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 4 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 2812 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 812 for page 2
Harris, 77084
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Try 1 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 1999 for page 5
Harris, 77083
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77086
There are 7695 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 1695 for page 4
Harris, 77085
There are 5545 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 1545 for page 3
Harris, 77088
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 4
	Try 1 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 5
Harris, 77087
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Try 1 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 5
Harris, 77090
There are 7109 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Num Results: 1109 for page 4
Harris, 77089
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77092
There are 9376 number of addresses known in this zipcode.
	Num Results: 1999 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 4
	Num Results: 1376 for page 5
Harris, 77091
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Try 4 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 4
	Try 1 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 5
Harris, 77094
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 3623 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 1623 for page 2
Harris, 77093
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77096
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 8738 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2

	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 738 for page 5
Harris, 77095
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77098
There are 4465 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 465 for page 3
Harris, 77099
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 9789 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 4
	Try 1 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 1789 for page 5
Harris, 77204
There are 20 number of addresses known in this zipcode.
	Num Results: 20 for page 1
Harris, 77217
There are 0 number of addresses known in this zipcode.
	Num Results: 0 for page 1
Harris, 77249
There are 40 number of addresses known in this zipcode.
	Num Results: 40 for page 1
Harris, 77251
There are 5 number of addresses known in this zipcode.
	Num Results: 5 for page 1
Harris, 77266
There are 0 number of addresses known in this zipcode.
	Num Results: 0 for page 1
Harris, 77268
There are 0 number of addresses known in this zipcode.
	Num Results: 0 for page 1
Harris, 77271
There are 1 number of addresses known in this zipcode.
	Num Results: 1 for page 1
Harris, 77284
There are 1 number of addresses known in this zipcode.
	Num Results: 1 for page 1
Harris, 77289
There are 0 number of addresses known in this zipcode.
	Num Results: 0 for page 1
Harris, 77336
There are 8701 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 4
	Num Results: 701 for page 5
Harris, 77339
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Try 1 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 5
Harris, 77338
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77345
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 9843 number of addresses known in this zipcode.
	Num Results: 1995 for page 1
	Try 2 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 9843 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 4
	Num Results: 1843 for page 5
Harris, 77346
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 4 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 5 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 6 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Try 1 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 5
Harris, 77357
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77373
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Try 1 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 1998 for page 5
Harris, 77375
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Try 1 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 5
Harris, 77377
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77379
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.

	Try 2 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 4
	Try 1 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 5
Harris, 77383
There are 4 number of addresses known in this zipcode.
	Num Results: 4 for page 1
Harris, 77389
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77388
There are 10000 number of addresses known in this zipcode.
	Num Results: 1999 for page 1
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Try 1 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 5
Harris, 77396
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 4
	Try 1 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 5
Harris, 77401
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 6754 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Num Results: 754 for page 4
Harris, 77410
There are 2 number of addresses known in this zipcode.
	Num Results: 2 for page 1
Harris, 77429
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Try 4 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Try 5 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Try 6 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Try 7 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77433
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77447
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 9207 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 1207 for page 5
Harris, 77450
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Try 1 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 5
Harris, 77449
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77484
There are 7779 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Num Results: 1779 for page 4
Harris, 77493
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Try 1 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 5
Harris, 77503
There are 7340 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 1340 for page 4
Harris, 77502
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Try 4 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Try 5 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Try 6 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77505
There are 7654 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Num Results: 1654 for page 4
Harris, 77504
There are 5806 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 1806 for page 3
Harris, 77507
There are 528 number of addresses known in this zipcode.
	Num Results: 528 for page 1
Harris, 77506
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 8584 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 584 for page 5
Harris, 77521
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 4 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 2 didn't parse correctly. Trying again up to 10 times total.

	Try 3 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77520
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77530
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77532
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77536
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 4
	Try 1 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 5
Harris, 77546
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 4
	Try 1 for page 5 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 5
Harris, 77547
There are 3063 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Num Results: 1063 for page 2
Harris, 77562
There are 5391 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 1391 for page 3
Harris, 77571
There are 10000 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Try 3 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 3
	Try 1 for page 4 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 4
	Num Results: 2000 for page 5
Harris, 77586
There are 9798 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Num Results: 2000 for page 3
	Num Results: 2000 for page 4
	Num Results: 1798 for page 5
Harris, 77587
	Try 1 for page 1 didn't parse correctly. Trying again up to 10 times total.
There are 5671 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Try 1 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Try 2 for page 3 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 1671 for page 3
Harris, 77598
There are 4794 number of addresses known in this zipcode.
	Num Results: 2000 for page 1
	Try 1 for page 2 didn't parse correctly. Trying again up to 10 times total.
	Num Results: 2000 for page 2
	Num Results: 794 for page 3

In [6]:
print(county_Zip_Adds.head())
county_Zip_Adds.to_csv("../data/rawdata/All_Addresses.csv",index=False)

     zip                              address        lat         lng
0  77002  804 CHELSEA BLVD, HOUSTON, TX 77002  29.730016  -95.388165
1  77002  806 CHELSEA BLVD, HOUSTON, TX 77002  29.730009  -95.388151
2  77002  808 CHELSEA BLVD, HOUSTON, TX 77002  29.730001  -95.388138
3  77002    4916 TRAVIS ST, HOUSTON, TX 77002  29.730105  -95.387377
4  77002  810 CHELSEA BLVD, HOUSTON, TX 77002  29.729993  -95.388125

The random creation cell doesn't work for the random selection. We need 500 valid results, and some of the addresses aren't listed. The random cell will be put in the zillow api, as it requires the call to tell if an address is valid.

In [68]:
group_Adds = pd.DataFrame(data={"zip":"", "address":"", "lat":"", "lng":""}, index = [0])
total_Houses = pd.Series(data=zips,index=zips)

for i in range(len(zips)):#len(total_Addresses) doesn't work cause there was another random error that caused a retry
    #in the middle of assignment of values to the dataframe. While not affecting the actual list of values, total_Addresses
    #now has a single repeat value for one of the functions. Total addresses will now be done with the count function
    #of individual groupby after county_Zip_Adds has been made, though it is less efficient
    df = county_Zip_Adds.loc[county_Zip_Adds["zip"] == str(zips[i])]
    #Finds only exact matches as \\bWord\\b finds only the word, and not anything that contains it, unless other chars are buffered by space away from it
    df = df.loc[(df["address"].str.contains("\\bUNIT\\b|\\bAPT\\b|\\bSTE\\b|\\bBSMT\\b|\\bFL\\b|\\bHNGR\\b|\\bLOT\\b|\\bRM\\b|\\bSLIP\\b|\\bSTE\\b|\\bTRLR\\b") == False)]
    df = df.loc[df["address"].str.startswith(("0","1","2","3","4","5","6","7","8","9"))]
    df = df.reset_index(drop=True)
    length = len(df.index)
    total_Houses[zips[i]] = length
    
    if length >= 500:
        rands = random.sample(range(0,length),500)
        group_Adds = group_Adds.append(df.iloc[rands],ignore_index = True)
        
group_Adds = group_Adds.drop([0])
group_Adds = group_Adds.reset_index(drop=True)

In [74]:
group_Adds.to_csv("../data/cleandata/randomly_Sampled_Addresses.csv",index=False)

In [70]:
group_Adds.head()

     zip                                address        lat         lng
0  77002  703 ST JOSEPH PKWY, HOUSTON, TX 77002  29.751887  -95.372731
1  77002     909 COMMERCE ST, HOUSTON, TX 77002  29.764344  -95.360258
2  77002        4125 MAIN ST, HOUSTON, TX 77002  29.735709  -95.381456
3  77002     700 CONGRESS ST, HOUSTON, TX 77002  29.763529  -95.363124
4  77002        1700 MAIN ST, HOUSTON, TX 77002  29.751093  -95.369846

In [73]:
total_Addresses = county_Zip_Adds["zip"].value_counts()
total_Addresses.to_csv("../data/cleandata/Total_Addresses_With_Apartments.csv")
total_Houses.to_csv("../data/cleandata/Total_Addresses_Without_Apartments.csv")

Everything below this cell contains only code used for testing the code above and contributes nothing to the actual intended use of this code

In [27]:
df = county_Zip_Adds.loc[county_Zip_Adds["zip"] == str(zips[0])]
df = df.loc[(df["address"].str.contains("UNIT") == False)]
df = df.loc[(df["address"].str.contains("APT") == False)]
df.head()

     zip                              address        lat         lng
0  77002  804 CHELSEA BLVD, HOUSTON, TX 77002  29.730016  -95.388165
1  77002  806 CHELSEA BLVD, HOUSTON, TX 77002  29.730009  -95.388151
2  77002  808 CHELSEA BLVD, HOUSTON, TX 77002  29.730001  -95.388138
3  77002    4916 TRAVIS ST, HOUSTON, TX 77002  29.730105  -95.387377
4  77002  810 CHELSEA BLVD, HOUSTON, TX 77002  29.729993  -95.388125

In [20]:
print(len(zips))
print(len(total_Addresses))

146
147

In [42]:
s1 = pd.Series(["Mouse and Moose","Monkey","Marigold","Doomwhale","Bird"])
s1.str.contains("\\bMouse\\b|\\bBird\\b")

0     True
1    False
2    False
3    False
4     True
dtype: bool

In [49]:
s1 = pd.Series(["Mouse and Moose","123 Monkey","58, Marigold","Doomwhale, 58","Bird"])
s1.str.startswith(("0","1","2","3","4","5","6","7","8","9"))

0    False
1     True
2     True
3    False
4    False
dtype: bool

In [67]:
total_Addresses["77004"]

8388